ezpublish:
    system:
        admin_group:
            fieldtypes:
                ezrichtext:
                    custom_tags: [ezbutton, ezyoutube, eztwitter, factbox, jsfiddle]
    ezrichtext:
        custom_tags:
            ezbutton:
                template: '@ezdesign/fields/ezrichtext/custom_tags/ezbutton.html.twig'
                icon: '/bundles/ezplatformadminui/img/ez-icons.svg#form'
                attributes:
                    url:
                        type: 'string'
                        required: true
                    title:
                        type: 'string'
                        required: true
                    target:
                        type: 'string'
                        required: false
                    class:
                        type: 'string'
                        required: false

            ezyoutube:
                template: '@ezdesign/fields/ezrichtext/custom_tags/ezyoutube.html.twig'
                icon: '/bundles/ezplatformadminui/img/ez-icons.svg#video'
                attributes:
                    video_url:
                        type: 'string'
                        required: true
                    width:
                        type: 'number'
                        required: true
                        default_value: 640
                    height:
                        type: 'number'
                        required: true
                        default_value: 360
                    autoplay:
                        type: 'boolean'
                        default_value: false

            eztwitter:
                template: '@ezdesign/fields/ezrichtext/custom_tags/eztwitter.html.twig'
                icon: '/bundles/ezplatformadminui/img/ez-icons.svg#twitter'
                attributes:
                    tweet_url:
                        type: 'string'
                        required: true
                    # see https://dev.twitter.com/web/embedded-tweets/parameters
                    cards:
                        type: 'choice'
                        required: false
                        default_value: ''
                        choices: ['', 'hidden']
                    conversation:
                        type: 'choice'
                        default_value: ''
                        choices: ['', 'none']
                    theme:
                        type: 'choice'
                        default_value: 'light'
                        required: true
                        choices: ['light', 'dark']
                    link_color:
                        type: 'string'
                        default_value: ''
                    width:
                        type: 'number'
                        default_value: 500
                    lang:
                        type: 'string'
                        default_value: 'en'
                    dnt:
                        type: 'boolean'
                        default_value: true

            factbox:
                template: '@ezdesign/fields/ezrichtext/custom_tags/factbox.html.twig'
                icon: '/bundles/ezplatformadminui/img/ez-icons.svg#about'
                attributes:
                    title:
                        type: 'string'

            jsfiddle:
                template: '@ezdesign/fields/ezrichtext/custom_tags/jsfiddle.html.twig'
                icon: '/bundles/ezplatformadminui/img/ez-icons.svg#components'
                attributes:
                    user_id:
                        type: 'string'
                        required: true
                    script_id:
                        type: 'string'
                        required: true
                    version_id:
                        type: 'string'
                        required: true

