services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\Command\:
        resource: '../../../src/AppBundle/Command/*'

    AppBundle\Command\UpdatePackageListCommand:
        arguments:
            $adminId: '%app.admin_id%'
