services:
    _defaults:
        autowire: true
        autoconfigure: true

    AppBundle\Controller\:
        resource: '../../../src/AppBundle/Controller/*'

    AppBundle\Controller\DownloadController:
        arguments:
            $releaseContainerLocationId: '%release_container_location_id%'
            $betaContainerLocationId: '%beta_container_location_id%'

    AppBundle\Controller\BlogController:
        arguments:
            $blogLocationId: '%blog.location_id%'
            $blogPostsLimit: '%blog.posts_limit%'

    AppBundle\Controller\PackageController:
        arguments:
            $router: '@router.default'
            $packageListLocationId: '%packages.location_id%'
            $packageListCardsLimit: '%packages.cards_limit%'
            $packageCategoriesParentTagId: '%packages.categories_parent_tag_id%'

    AppBundle\Controller\TagController:
        arguments:
            $relatedContentLimit: '%eztags.default.tag_view.related_content_list.limit%'
