services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\Event\Subscriber\PublishOnLastStageSubscriber:
        arguments:
            $publishOnLastStageWorkflows: '%app.workflow.publish_on_last_stage%'

    AppBundle\Event\Subscriber\NotificationSenderSubscriber:
        arguments:
            $recipients: '%packages.submission_mail_notification_recipients%'

    AppBundle\Event\Subscriber\ReleaseSubscriber:
        arguments:
            $releaseContentTypeId: '%app.release_content_type_id%'
            $downloadSectionLocationId: '%app.download_section_location_id%'
