services:
    _defaults:
        autowire: true
        autoconfigure: true

    AppBundle\Event\Workflow\PublishOnLastStageSubscriber:
        arguments:
            $publishOnLastStageWorkflows: '%app.workflow.publish_on_last_stage%'
