services:
    app.packagist_api_client:
        class: Packagist\Api\Client
    app.packagist_api_mapper:
        class: AppBundle\Mapper\PackageMapper
        arguments: ['%packages.excluded_maintainers%']
    app.packagist_service_provider:
        class: AppBundle\Service\Packagist\PackagistServiceProvider
        arguments:
            - '@app.packagist_api_client'
            - '@app.packagist_api_mapper'
