services:
    AppBundle\View\Template\PackageListTemplate: ~

    Pagerfanta\View\DefaultView:
        public: false
        arguments:
            $template: '@AppBundle\View\Template\PackageListTemplate'
        tags:
            - { name: pagerfanta.view, alias: package_list }
