services:
    _defaults:
        autowire: true
        autoconfigure: true

    EzSystems\EzPlatformAdminUi\Component\ScriptComponent:
            arguments:
                $src: "/assets/js/hotjar.js"
            tags:
                - { name: ezplatform.admin_ui.component, group: 'script-head' }
