services:
    _defaults:
        autowire: true
        autoconfigure: true

    AppBundle\Service\:
        resource: '../../../src/AppBundle/Service/*'

    Netgen\TagsBundle\API\Repository\TagsService: '@eztags.api.service.tags'

    AppBundle\Service\Package\PackageService:
        arguments:
            $parentLocationId: '%packages.location_id%'
            $tagsService: '@ezpublish.api.service.tags'
            $packageContributorId: '%package_contributor_id%'

    AppBundle\Service\Cache\CacheService:
        arguments:
            $cacheExpirationTime: '%packages.cache_expiration_time%'

    AppBundle\Service\GitHub\GitHubServiceProvider:
        arguments:
            $authenticationToken: '%env(GITHUB_TOKEN)%'

    EzSystems\EzPlatformAdminUi\UI\Dataset\ContentDraftsDataset: ~
