services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\Twig\:
        resource: '../../../src/AppBundle/Twig/*'
        tags:
            - name: twig.extension

    AppBundle\Twig\AppConfigExtension:
        $releasesFolderLocationId: '%app.releases_folder_location_id%'
