services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\Validator\:
        resource: '../../../src/AppBundle/Validator/*'

    AppBundle\Validator\Constraints\PackageDbNotExistsConstraintValidator:
        arguments:
            $packageContributorId: '%package_contributor_id%'
